export const mockData = [
  {
    id: 1,
    firstName: 'Иван Иванович',
    lastName: 'Иванов',
    avatar: '/avatar.png',
    link: '/ivanov-ivan',
    position: 'Junior UI/UX designer',
    address: 'Россия, Красноярск',
    statistics: {
      available: 32,
      planned: 8,
      used: 4,
    },
    vacationHistory: [
      {
        id: 1,
        type: 'Отпуск',
        dateStart: '03 марта 2023',
        dateEnd: '10 марта 2023',
        duration: '7',
      },
      {
        id: 2,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 3,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 4,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 5,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 6,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 7,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 8,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
    ],
  },
  {
    id: 1,
    firstName: 'Петр Петрович',
    lastName: 'Петров',
    avatar: '/avatar.png',
    link: '/petrov-petr',
    position: 'Junior UI/UX designer',
    address: 'Россия, Красноярск',
    statistics: {
      available: 43,
      planned: 9,
      used: 23,
    },
    vacationHistory: [
      {
        id: 1,
        type: 'Отпуск',
        dateStart: '03 марта 2023',
        dateEnd: '10 марта 2023',
        duration: '7',
      },
      {
        id: 2,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 3,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 4,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 5,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 6,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 7,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
      {
        id: 8,
        type: 'Отгул',
        dateStart: '03 марта 2023',
        dateEnd: '4 марта 2023',
        duration: '1',
      },
    ],
  },
];
